import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules = ['Swift 基础','Swift 6 与并发','SwiftUI','原生工程实践'];
const files = (await readdir(path.join(root,'content'))).filter(f => f.endsWith('.json'));
const lessons = (await Promise.all(files.map(async file => JSON.parse(await readFile(path.join(root,'content',file),'utf8'))))).flat().sort((a,b)=>a.id-b.id);
if (lessons.length !== 44 || lessons.some((l,i)=>l.id !== i+1)) throw new Error('Expected exactly lessons 1..44');
for (const l of lessons) {
  if (!/^[a-z0-9-]+$/.test(l.slug) || !modules.includes(l.module) || l.sections.length < 3 || !l.exercise.solution || l.sources.length < 1 || !l.lab.path) throw new Error(`Invalid lesson ${l.id}`);
  if (!Number.isInteger(l.quiz.answer) || !l.quiz.options[l.quiz.answer]) throw new Error(`Invalid quiz ${l.id}`);
}
const filename = l => `${String(l.id).padStart(4,'0')}-${l.slug}.html`;
const link = (id,prefix='') => `${prefix}${filename(lessons[id-1])}`;
const list = items => `<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const refs = [ ['glossary','术语与前端迁移'],['swift-cheatsheet','Swift 语法速查'],['concurrency-map','并发与版本地图'],['swiftui-dataflow','SwiftUI 数据流'],['native-checklist','原生工程检查表'] ];
function shell(title, body, prefix='', className='') {
  return `<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="面向 Web 前端工程师的 Swift 6、SwiftUI 与 Apple 原生开发课程"><title>${escape(title)} · Swift Native Lab</title><link rel="stylesheet" href="${prefix}assets/course.css"><script defer src="${prefix}assets/course.js"></script></head><body><a class="skip" href="#main">跳到正文</a><header class="site-header"><a class="brand" href="${prefix}index.html">SWIFT / NATIVE LAB</a><nav class="header-links" aria-label="全站导航"><a href="${prefix}index.html#curriculum">课程</a><a href="${prefix}index.html#references">速查</a><a href="${prefix}README.md">运行指南</a></nav></header><main id="main" class="page ${className}">${body}</main><footer class="footer">为 Web 前端工程师设计 · 官方资料核对：2026-09-22 · 内容与示例可离线阅读；外部资料需联网 · 学习问题可以随时带回 Codex</footer></body></html>\n`;
}
await mkdir(path.join(root,'lessons'),{recursive:true});
for (const l of lessons) {
 const sections = l.sections.map((s,i)=>`<section id="part-${i+1}"><h2>${escape(s.title)}</h2>${s.html}</section>`).join('\n');
 const prereq = l.prerequisites.length ? l.prerequisites.map(id=>`<a href="${link(id)}">${String(id).padStart(2,'0')} ${escape(lessons[id-1].title)}</a>`).join(' · ') : '无需 Swift 前置知识';
 const quiz = `<form class="quiz" data-quiz data-answer="${l.quiz.answer}" data-explanation="${escape(l.quiz.explanation)}"><fieldset><legend>${escape(l.quiz.question)}</legend>${l.quiz.options.map((o,i)=>`<label><input type="radio" name="answer" value="${i}">${escape(o)}</label>`).join('')}</fieldset><button type="submit">检查答案</button><p class="feedback" role="status" aria-live="polite"></p><noscript><p>脚本未启用。参考答案：${escape(l.quiz.options[l.quiz.answer])}。${escape(l.quiz.explanation)}</p></noscript></form>`;
 const body = `<div class="lesson-layout"><aside class="toc" aria-label="本课导航"><strong>LESSON ${String(l.id).padStart(2,'0')}</strong>${l.sections.map((s,i)=>`<a href="#part-${i+1}">${escape(s.title)}</a>`).join('')}<a href="#practice">动手练习</a><a href="#quiz">即时自测</a><a href="#sources">官方资料</a><a href="../reference/glossary.html">术语速查 ↗</a></aside><article><div class="eyebrow">${escape(l.module)} / ${l.minutes} MIN</div><h1>${escape(l.title)}</h1><p class="lede">${escape(l.summary)}</p><p class="meta">前置：${prereq}</p><div class="objective"><strong>本课的一个成果</strong>${escape(l.objective)}</div>${sections}<section class="lab"><h3>对应可运行实验</h3><p><a href="../${escape(l.lab.path)}">${escape(l.lab.label)}</a></p><pre><code>${escape(l.lab.command)}</code></pre><p class="source-note">终端命令默认在 swift-learning 根目录执行；说明为 Xcode 操作时，跟随项目 README。</p></section><section id="practice"><h2>动手：${escape(l.exercise.prompt)}</h2><ol>${l.exercise.steps.map(x=>`<li>${escape(x)}</li>`).join('')}</ol><div class="callout"><strong>验收现象</strong><p>${escape(l.exercise.expected)}</p></div><details><summary>先独立完成，再展开参考解法</summary>${l.exercise.solution}</details></section><section><h2>从前端迁移时，留意这些误区</h2>${list(l.pitfalls.map(escape))}</section><section id="quiz"><h2>即时自测</h2>${quiz}</section><section><h2>合上页面，尝试回忆</h2>${list(l.retrieval.map(escape))}<p class="source-note">建议在次日、第 3 天与第 7 天重做练习；这是起始复习节奏，可按遗忘情况调整。答错时先定位原因，再看解法。</p></section><section id="sources" class="sources"><h2>回到一手资料</h2><p>主读：第一项。正文是原创教学示例；语言与 API 语义以这些官方资料为依据。</p>${list(l.sources.map(s=>`<a href="${escape(s.url)}">${escape(s.title)}</a>`))}<p>跨课速查：${refs.map(([slug,title])=>`<a href="../reference/${slug}.html">${title}</a>`).join(' · ')}</p></section><section class="finish"><p>遇到不清楚的地方，直接向 Codex 提问：<strong>“第 ${l.id} 课，我预测……，实际……，请帮我理解原因。”</strong></p><button data-complete="${l.id}" aria-pressed="false">我已独立完成练习</button> <button class="secondary" data-export>导出进度</button><p class="source-note">勾选只保存本浏览器的自报进度，不代表已通过能力验收；正式掌握情况写入 learning-records。</p></section><nav class="pager" aria-label="课程序列">${l.id>1?`<a href="${link(l.id-1)}">← ${escape(lessons[l.id-2].title)}</a>`:'<a href="../index.html">← 课程地图</a>'}${l.id<44?`<a href="${link(l.id+1)}">${escape(lessons[l.id].title)} →</a>`:'<a href="../CAPSTONE.md">毕业项目验收 →</a>'}</nav></article></div>`;
 await writeFile(path.join(root,'lessons',filename(l)),shell(l.title,body,'../'));
}
const moduleContent = modules.map((module,i)=>`<section data-module-section><div class="module-head"><h2>0${i+1} / ${module}</h2><span class="meta">${lessons.filter(l=>l.module===module).length} LESSONS</span></div><div class="lesson-grid">${lessons.filter(l=>l.module===module).map(l=>`<article class="lesson-card" data-lesson-card="${l.id}" data-module="${escape(module)}"><div class="number">${String(l.id).padStart(2,'0')}</div><div><h3><a href="lessons/${filename(l)}">${escape(l.title)}</a></h3><p>${escape(l.objective)}</p><span class="meta">${l.minutes} 分钟 · </span><span class="badge" data-status>待学习</span></div></article>`).join('')}</div></section>`).join('');
const home = `<section class="hero"><div><div class="eyebrow">WEB ENGINEER → APPLE NATIVE ENGINEER</div><h1>从熟悉的前端，<br>走进原生世界。</h1><p class="intro">一套可以动手、验证、反复回看的 Swift 学习工作室。建立语言基础，理解并发边界，再把它们变成 iPhone 与 Mac 上真正运行的应用。</p><a href="lessons/${filename(lessons[0])}">从第 01 课开始 →</a></div><aside class="hero-panel"><div class="metric">44 / 3 / 5</div><h2>44 节课程 · 3 个项目 · 5 份速查</h2><p>Swift 6 语言模式<br>SwiftUI + Observation + SwiftData<br>iOS 17+ / macOS 14+</p><p>一次准备完整主线，按自己的节奏练习。代码带中文注释，核心实验可离线运行。</p><a href="CURRICULUM.md">查看完整课程与学习节奏 ↗</a></aside></section><div class="path"><span><b>01 — 语言与建模</b><small>把数据约束写进类型</small></span><span><b>02 — 并发与边界</b><small>让异步工作可推理</small></span><span><b>03 — 声明式界面</b><small>用状态驱动原生 UI</small></span><span><b>04 — 工程与交付</b><small>从演示走向可靠应用</small></span></div><section><h2>这次学习怎样才算有效？</h2><p>每课先预测代码行为，再运行并修改示例，最后独立完成一个小练习。不要用“看懂了”代替“能写出来”。网页进度仅在你主动勾选时更新。</p><div class="progress-line"><progress value="0" max="44" aria-label="课程练习进度"></progress><span data-progress-count>0 / 44 课已练习</span><button class="secondary" data-export>导出进度</button></div><p class="source-note">建议每周 4 次、每次 45–75 分钟；预计 12–16 周含项目练习。分钟数为单课首轮学习估计，深入项目可花更久。直接打开 HTML 即可阅读；统一浏览器地址有助于保留进度。</p></section><section id="curriculum"><h2>完整课程地图</h2><div class="tools"><label for="search">查找课程</label><input id="search" data-search type="search" placeholder="例如：Optional、actor、导航、测试" autocomplete="off"></div><div class="filters" role="group" aria-label="按模块筛选"><button data-filter="all" aria-pressed="true">全部</button>${modules.map(m=>`<button data-filter="${m}" aria-pressed="false">${m}</button>`).join('')}</div><p class="meta" role="status" data-search-result>显示 44 节课程</p>${moduleContent}</section><section id="projects"><h2>把知识变成运行中的程序</h2><div class="resources-grid"><a href="examples/SwiftFoundations/README.md"><strong>SwiftFoundations</strong><br>语法、建模、序列化与测试</a><a href="examples/ConcurrencyLab/README.md"><strong>ConcurrencyLab</strong><br>结构化并发、隔离与错误处理</a><a href="examples/NativeStudy/README.md"><strong>NativeStudy</strong><br>iOS / macOS 学习管理应用</a></div><p><a href="VERIFICATION.md">查看实际构建与测试记录</a> · <a href="CAPSTONE.md">毕业项目任务书</a></p></section><section id="references"><h2>随时翻阅的速查卡</h2><div class="resources-grid">${refs.map(([slug,title])=>`<a href="reference/${slug}.html">${title} ↗</a>`).join('')}<a href="RESOURCES.md">官方文档与实践社区 ↗</a></div></section>`;
await writeFile(path.join(root,'index.html'),shell('课程地图',home));
const table=lessons.map(l=>`| ${String(l.id).padStart(2,'0')} | [${l.title}](lessons/${filename(l)}) | ${l.prerequisites.join(', ')||'无'} | ${l.objective} |`).join('\n');
await writeFile(path.join(root,'CURRICULUM.md'),`# Swift / Native Lab 完整课程大纲\n\n以 [MISSION.md](MISSION.md) 为目标。44 课已提供完整正文、练习、解答和官方资料，并非待生成占位。主线按编号学习；单课约 20–35 分钟，项目修改与复习另计。\n\n## 学习路径与验收\n\n| 阶段 | 内容 | 项目成果 | 阶段验收 |\n|---|---|---|---|\n| 1 / 01–14 | Swift 类型、控制流、建模、内存、测试 | SwiftFoundations | 独立完成一个有输入校验的 CLI，测试空值、非法值、序列化 |\n| 2 / 15–24 | Swift 6、结构化并发、actor、网络 | ConcurrencyLab | 解释隔离边界，验证取消、HTTP 失败、乱序与共享状态 |\n| 3 / 25–34 | SwiftUI、Observation、SwiftData | NativeStudy | 两个平台可运行增删改查，能解释每份状态的所有者 |\n| 4 / 35–44 | 测试、调试、平台适配、交付 | NativeStudy 毕业扩展 | 依据 CAPSTONE.md 提供行为、失败路径和设备验收证据 |\n\n## 逐课内容\n\n| 课 | 主题 | 前置课 | 可观察成果 |\n|---|---|---|---|\n${table}\n\n## 节奏与复习\n\n建议 12–16 周，每周 4 次、每次 45–75 分钟。一次一到两课：预测 → 运行 → 修改 → 从空白重写关键部分。次日、3 天和 7 天后回忆概念，再按掌握情况调整，不机械追求完成课数。每完成一个阶段，做一次不看答案的里程碑验收。\n\n## 后续专项，不阻塞主线\n\nWidgetKit / App Intents、通知与 APNs、CloudKit 同步、Core Data 旧项目迁移、Combine 维护、StoreKit、Metal、音视频、watchOS / visionOS、深入 SwiftSyntax 宏实现与性能优化可在完成主线后按职业项目选择。当前课程提供相关边界与官方入口，不宣称覆盖每一种 Apple 框架。\n`);
console.log(`Generated ${lessons.length} lessons, index.html and CURRICULUM.md`);
